---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(tidyverse)
library(broom)
library(modelr)
library(here)
library(ggplot2)
library(reshape2)
library(grid)
library("GGally")
library(tidyverse)
library(psych)
library(summarytools)
library("dplyr")
library("ggpubr")
library (rcompanion)
library(readxl)
library(car)
library(lmtest)
library(tidyverse)
library(caret)
library(leaps)
library(olsrr)
theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)


```

```{r ETL}
dados = read_csv(here::here("IPIP-TCI-Subjects_final.csv")) 

cols(
  codigoSHA = col_character(),
  projetoAtual = col_character(),
  Role = col_character(),
  xpPosGraduate = col_double(),
  xpPosGraduatedVirtus = col_double(),
  Age = col_double(),
  Gender = col_character(),
  tci_TeamVision = col_double(),
  tci_TaskOrientation = col_double(),
  tci_SupportForInovation = col_double(),
  tci_ParticipativeSafety = col_double(),
  iptc = col_double(),
  ipip_Extraversion = col_double(),
  ipip_Agreeableness = col_double(),
  ipip_Conscientiousness = col_double(),
  ipip_Neuroticism = col_double(),
  ipip_Openness = col_double()
)



```


```{r}
dados %>%
  group_by(projetoAtual) %>%
  count()

```

```{r}
dadosEquipesGrandes <- dados%>%filter(projetoAtual!="Gertec - MDM",projetoAtual!="HP - Windows Device Drivers 2020", projetoAtual!="Ingeteam - Agile-Installer", projetoAtual!="Inovatic - MDA Middleware", projetoAtual!="Inovatic - SCM", projetoAtual!="Motorola - MOTOTRBO Application Explorer")
```

```{r}
dadosEquipesGrandes %>%
  group_by(projetoAtual) %>%
  count()

```



```{r}

#psych::describe(dados)

#Média, Mediana, Desvio padrão, coeficiente de variação, minimo e máximo
descr(dadosEquipesGrandes, stats = c("mean", "med", "sd", "cv", "min", "max"), transpose = TRUE)

```

```{r}
#summary
dfSummary(dadosEquipesGrandes)
```

```{r}
#Frequencia Masculino e Femino

freq(dados$Gender, order = "freq", rows = 1:5, headings = FALSE, report.nas = FALSE, totals = FALSE)

```

```{r}
#Frequencia da idade por grupos

AgeGrp <- as.character(cut(dados$Age, breaks=c(20,25,30,35,40,Inf),
          labels=c('20-25', '26-30', '31-35', '36-40', 'Over 40')))

with(dados, stby(data = Age, INDICES = AgeGrp, 
                   FUN = descr))

```

```{r}
#Frequencia da xp pos graduado por grupos

PosGraduateGrp <- as.character(cut(dados$xpPosGraduate, breaks=c(0,3,6,10,14,Inf),
          labels=c('0-3', '4-6', '7-10', '11-14', 'Over 14')))

with(dados, stby(data = Age, INDICES = PosGraduateGrp, 
                   FUN = descr))

```


```{r}
#Frequencia da xp pos graduado no virtus por grupos

PosGraduateGrpVirtus <- as.character(cut(dados$xpPosGraduatedVirtus, breaks=c(0,3,6,10,14,Inf),
          labels=c('0-3', '4-6', '7-10', '11-14', 'Over 14')))

with(dados, stby(data = Age, INDICES = PosGraduateGrpVirtus, 
                   FUN = descr))

```

```{r}
#Frequencia Role

freq(dados$Role, order = "freq", rows = 1:5, headings = FALSE, report.nas = FALSE, totals = FALSE)

```

```{r}
boxplot(dadosEquipesGrandes$tci_TeamVision, xlim = c(0, 2), ylim = c(0, 5))
#boxplot(dados$tci_TaskOrientation, xlim = c(0, 2), ylim = c(0, 5))
abline(h=1,col="red",lty=2)
abline(h=2,col="red",lty=2)
abline(h=3,col="red",lty=2)
abline(h=4,col="red",lty=2)
abline(h=5,col="red",lty=2)


```
```{r}
#boxplot(dados$tci_TeamVision, xlim = c(0, 2), ylim = c(0, 5))
boxplot(dadosEquipesGrandes$tci_TaskOrientation, xlim = c(0, 2), ylim = c(0, 5))
abline(h=1,col="red",lty=2)
abline(h=2,col="red",lty=2)
abline(h=3,col="red",lty=2)
abline(h=4,col="red",lty=2)
abline(h=5,col="red",lty=2)

```
```{r}
#boxplot(dados$ , xlim = c(0, 2), ylim = c(0, 5))
boxplot(dadosEquipesGrandes$iptc, xlim = c(0, 2), ylim = c(0, 5))
abline(h=1,col="red",lty=2)
abline(h=2,col="red",lty=2)
abline(h=3,col="red",lty=2)
abline(h=4,col="red",lty=2)
abline(h=5,col="red",lty=2)




```
```{r}
#boxplot(dados$tci_TeamVision, xlim = c(0, 2), ylim = c(0, 5))
#bboxplot(dados$tci_TaskOrientation, xlim = c(0, 2), ylim = c(0, 5))
#babline(h=1,col="red",lty=2)
#babline(h=2,col="red",lty=2)
#babline(h=3,col="red",lty=2)
#babline(h=4,col="red",lty=2)
#babline(h=5,col="red",lty=2)

mar.orig <- par()$mar
par(mar=c(9,5,3,0))
boxplot(dadosEquipesGrandes$tci_TeamVision, dadosEquipesGrandes$tci_TaskOrientation, dadosEquipesGrandes$tci_SupportForInovation, dadosEquipesGrandes$tci_ParticipativeSafety, dadosEquipesGrandes$iptc,
main = "Team climate factors’ scores",
names = c("Vision", "Task Orientation", "Support for Inovation", "Participative Safety", "IPTC"),
las = 1,
xlim = c(0, 18),
ylim = c(0, 5),
at = c(0.5, 3.5, 8.5, 13.5, 17),
varwidth = TRUE,
ylab = "Score of team climate factor"

)

abline(h=1,col="red",lty=2)
abline(h=2,col="red",lty=2)
abline(h=3,col="red",lty=2)
abline(h=4,col="red",lty=2)
abline(h=5,col="red",lty=2)
#par(mar = mar.orig)
```
```{r}
#boxplot(dados$tci_TeamVision, xlim = c(0, 2), ylim = c(0, 5))
#bboxplot(dados$tci_TaskOrientation, xlim = c(0, 2), ylim = c(0, 5))
#babline(h=1,col="red",lty=2)
#babline(h=2,col="red",lty=2)
#babline(h=3,col="red",lty=2)
#babline(h=4,col="red",lty=2)
#babline(h=5,col="red",lty=2)

mar.orig <- par()$mar
par(mar=c(9,5,3,0))
boxplot(dadosEquipesGrandes$ipip_Extraversion, dadosEquipesGrandes$ipip_Agreeableness, dadosEquipesGrandes$ipip_Conscientiousness, dadosEquipesGrandes$ipip_Neuroticism,dadosEquipesGrandes$ipip_Openness,
main = "Personality traits’ scores",
names = c("Extraversion", "Agreeableness", "Conscientiousness", "Neuroticism", "Openness"),
las = 1,
xlim = c(0, 10),
ylim = c(0, 100),
varwidth = TRUE,
at = c(0.5, 2.5, 5, 7.5, 9.5),
ylab = "Score of personality trait"

)

abline(h=30,col="red",lty=2)
abline(h=70,col="red",lty=2)

#par(mar = mar.orig)
```
```{r}
#Density plot - TCI


ggdensity(dados$tci_TeamVision, main = "Density plot of tci_TeamVision",
          xlab = "tci_TeamVision")

ggdensity(dados$tci_TaskOrientation, main = "Density plot of tci_TaskOrientation",
          xlab = "tci_TaskOrientation")

ggdensity(dados$tci_SupportForInovation, main = "Density plot of tci_SupportForInovation",
          xlab = "tci_SupportForInovation")

ggdensity(dados$tci_ParticipativeSafety, main = "Density plot of tci_ParticipativeSafety",
          xlab = "tci_ParticipativeSafety")

ggdensity(dados$iptc, main = "Density plot of iptc",
          xlab = "iptc")
```
```{r}
#Q-Q plot - TCI


ggqqplot(dados$tci_TeamVision, main = "Density plot of tci_TeamVision",
          xlab = "tci_TeamVision")

ggqqplot(dados$tci_TaskOrientation, main = "Density plot of tci_TaskOrientation",
          xlab = "tci_TaskOrientation")

ggqqplot(dados$tci_SupportForInovation, main = "Density plot of tci_SupportForInovation",
          xlab = "tci_SupportForInovation")

ggqqplot(dados$tci_ParticipativeSafety, main = "Density plot of tci_ParticipativeSafety",
          xlab = "tci_ParticipativeSafety")

ggqqplot(dados$iptc, main = "Density plot of iptc",
          xlab = "iptc")
```
```{r}
#Shapiro-Wilk’s test


shapiro.test(dados$tci_TeamVision)

shapiro.test(dados$tci_TaskOrientation)

shapiro.test(dados$tci_SupportForInovation)

shapiro.test(dados$tci_ParticipativeSafety)

shapiro.test(dados$iptc)
```
```{r}
#Density plot - IPIP


ggdensity(dados$ipip_Extraversion, main = "Density plot of ipip_Extraversion",
          xlab = "ipip_Extraversion")

ggdensity(dados$ipip_Agreeableness, main = "Density plot of ipip_Agreeableness",
          xlab = "ipip_Agreeableness")

ggdensity(dados$ipip_Conscientiousness, main = "Density plot of ipip_Conscientiousness",
          xlab = "ipip_Conscientiousness")

ggdensity(dados$ipip_Neuroticism, main = "Density plot of ipip_Neuroticism",
          xlab = "ipip_Neuroticism")

ggdensity(dados$ipip_Openness, main = "Density plot of ipip_Openness",
          xlab = "ipip_Openness")
```
```{r}
#Q-Q plot - IPIP


ggqqplot(dados$ipip_Extraversion, main = "Density plot of ipip_Extraversion",
          xlab = "ipip_Extraversion")

ggqqplot(dados$ipip_Agreeableness, main = "Density plot of ipip_Agreeableness",
          xlab = "ipip_Agreeableness")

ggqqplot(dados$ipip_Conscientiousness, main = "Density plot of ipip_Conscientiousness",
          xlab = "ipip_Conscientiousness")

ggqqplot(dados$ipip_Neuroticism, main = "Density plot of ipip_Neuroticism",
          xlab = "ipip_Neuroticism")

ggqqplot(dados$ipip_Openness, main = "Density plot of ipip_Openness",
          xlab = "ipip_Openness")
```

```{r}
#Shapiro-Wilk’s test 0 IPIP


shapiro.test(dadosEquipesGrandes$ipip_Extraversion)

shapiro.test(dadosEquipesGrandes$ipip_Agreeableness)

shapiro.test(dadosEquipesGrandes$ipip_Conscientiousness)

shapiro.test(dadosEquipesGrandes$ipip_Neuroticism)

shapiro.test(dadosEquipesGrandes$ipip_Openness)
```
```{r}
#Shapiro-Wilk’s test 0 TCI


shapiro.test(dadosEquipesGrandes$tci_TeamVision)

shapiro.test(dadosEquipesGrandes$tci_SupportForInovation)

shapiro.test(dadosEquipesGrandes$tci_TaskOrientation)

shapiro.test(dadosEquipesGrandes$tci_ParticipativeSafety)

shapiro.test(dadosEquipesGrandes$iptc)

```


```{r}
cor(dados$iptc,dados$ipip_Extraversion)
cor.test(dados$iptc,dados$ipip_Extraversion,method = "pearson")

ggplot(dados, aes(x=dados$iptc, y=dados$ipip_Extraversion))+geom_point()
```

```{r}

selecionar = select(dados, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "pearson")

```


```{r}

selecionar = select(dados, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "pearson")

```
```{r}

selecionar = select(dados, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "pearson")

```
```{r}

selecionar = select(dados, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "pearson")

```

```{r}

selecionar = select(dados, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "pearson")

```

```{r}

selecionar = select(dados, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "spearman")

```





```{r}

selecionar = select(dados, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "kendall")

```

```{r}
options(scipen = 999)
plotNormalHistogram (dadosEquipesGrandes$tci_TeamVision)

qqnorm (dadosEquipesGrandes$tci_TeamVision,
       ylab = "Sample Quantiles for Team Vision")
qqline (dadosEquipesGrandes$tci_TeamVision,
       col = "red")
shapiro.test(log10(dadosEquipesGrandes$tci_TeamVision))


T_tuk =  transformTukey (dadosEquipesGrandes$tci_TeamVision,
                     plotit = TRUE)
summary(T_tuk)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)


```
```{r}
options(scipen = 999)
plotNormalHistogram (dados$tci_TaskOrientation)

qqnorm (dados$tci_TaskOrientation,
       ylab = "Sample Quantiles for Team Vision")
qqline (dados$tci_TaskOrientation,
       col = "red")
shapiro.test(dados$tci_TaskOrientation)

T_log = log(dados$tci_TaskOrientation)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$tci_TaskOrientation)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$tci_TaskOrientation)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey (dados$tci_TaskOrientation,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)


```

```{r}
options(scipen = 999)
plotNormalHistogram (dados$tci_SupportForInovation)

qqnorm (dados$tci_SupportForInovation,
       ylab = "Sample Quantiles for Team Vision")
qqline (dados$tci_SupportForInovation,
       col = "red")
shapiro.test(dados$tci_SupportForInovation)

T_log = log(dados$tci_SupportForInovation)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$tci_SupportForInovation)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$tci_SupportForInovation)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey (dados$tci_SupportForInovation,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)


```
```{r}
options(scipen = 999)
plotNormalHistogram (dados$tci_ParticipativeSafety)

qqnorm (dados$tci_ParticipativeSafety,
       ylab = "Sample Quantiles for Team Vision")
qqline (dados$tci_ParticipativeSafety,
       col = "red")
shapiro.test(dados$tci_ParticipativeSafety)

T_log = log(dados$tci_ParticipativeSafety)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$tci_ParticipativeSafety)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$tci_ParticipativeSafety)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey (dados$tci_ParticipativeSafety,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)


```
```{r}
options(scipen = 999)
plotNormalHistogram (dados$iptc)

qqnorm (dados$iptc,
       ylab = "Sample Quantiles for IPTC")
qqline (dados$iptc,
       col = "pink")
shapiro.test(dados$iptc)

T_log = log(dados$iptc)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$iptc)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$iptc)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)

T_tuk =  transformTukey (dados$iptc,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)

```
```{r}
options(scipen = 999)
plotNormalHistogram (dados$ipip_Extraversion)

qqnorm (dados$ipip_Extraversion,
       ylab = "Sample Quantiles for IPTC")
qqline (dados$ipip_Extraversion,
       col = "pink")
shapiro.test(dados$ipip_Extraversion)

T_log = log(dados$ipip_Extraversion)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$ipip_Extraversion)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$ipip_Extraversion)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey (dados$ipip_Extraversion,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)

```
```{r}
options(scipen = 999)
plotNormalHistogram (dados$ipip_Agreeableness)

qqnorm (dados$ipip_Agreeableness,
       ylab = "Sample Quantiles for IPTC")
qqline (dados$ipip_Extraversion,
       col = "pink")
shapiro.test(dados$ipip_Agreeableness)

T_log = log(dados$ipip_Extraversion)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$ipip_Agreeableness)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$ipip_Agreeableness)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey (dados$ipip_Agreeableness,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)

```
```{r}
options(scipen = 999)
plotNormalHistogram (dados$ipip_Conscientiousness)

qqnorm (dados$ipip_Conscientiousness,
       ylab = "Sample Quantiles for IPTC")
qqline (dados$ipip_Conscientiousness,
       col = "pink")
shapiro.test(dados$ipip_Conscientiousness)

T_log = log(dados$ipip_Conscientiousness)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$ipip_Conscientiousness)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$ipip_Conscientiousness)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey (dados$ipip_Conscientiousness,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)

```

```{r}
options(scipen = 999)
plotNormalHistogram (dados$ipip_Neuroticism)

qqnorm (dados$ipip_Neuroticism,
       ylab = "Sample Quantiles for IPTC")
qqline (dados$ipip_Neuroticism,
       col = "pink")
shapiro.test(dados$ipip_Neuroticism)

T_log = log(dados$ipip_Neuroticism)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$ipip_Neuroticism)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$ipip_Neuroticism)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey (dados$ipip_Neuroticism,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)

```

```{r}
options(scipen = 999)
plotNormalHistogram (dados$ipip_Openness)

qqnorm (dados$ipip_Openness,
       ylab = "Sample Quantiles for IPTC")
qqline (dados$ipip_Openness,
       col = "pink")
shapiro.test(dados$ipip_Openness)

T_log = log(dados$ipip_Openness)
plotNormalHistogram(T_log)
qqnorm (T_log,
       ylab = "Sample Quantiles for Team Vision Log")
qqline (T_log,
       col = "red")
shapiro.test(T_log)

T_log10 = log10(dados$ipip_Openness)
plotNormalHistogram(T_log10)
qqnorm (T_log10,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log10,
       col = "blue")
shapiro.test(T_log10)

T_log2 = log2(dados$ipip_Openness)
plotNormalHistogram(T_log2)
qqnorm (T_log2,
       ylab = "Sample Quantiles for Team Vision Log 10")
qqline (T_log2,
       col = "blue")
shapiro.test(T_log2)


T_tuk =  transformTukey(dados$ipip_Openness,
                     plotit = FALSE)
plotNormalHistogram (T_tuk)
shapiro.test(T_tuk)

```
```{r}

selecionar = select(dados, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc)
cor(selecionar, method = "spearman")

```
```{r}

selecionar = select(dados, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "spearman")

```
```{r}

selecionar = select(dadosEquipesGrandes, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "spearman")

```
```{r}
selecionar = select(dadosEquipesGrandes, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "pearson")

```

```{r}


model = lm(iptc~ipip_Agreeableness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model)

# Visualizar o modelo

plot(dados$iptc~dados$ipip_Agreeableness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)

# Aleatoriedade dos resíduos
plot(model$residuals, pch = 16, col = "red")
```
```{r}




model = lm(iptc~ipip_Conscientiousness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model)

# Visualizar o modelo

plot(dados$iptc~dados$ipip_Conscientiousness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)

# Aleatoriedade dos resíduos
plot(model$residuals, pch = 16, col = "red")
```
```{r}

iptc_tuk =  transformTukey (dados$iptc,
                     plotit = FALSE)

Conscientiousness_tuk =  transformTukey (dados$ipip_Conscientiousness,
                     plotit = FALSE)

model = lm(iptc_tuk~Conscientiousness_tuk, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model)

# Visualizar o modelo

plot(iptc_tuk~Conscientiousness_tuk)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)

# Aleatoriedade dos resíduos
plot(model$residuals, pch = 16, col = "red")
```







```{r}



model = lm(tci_SupportForInovation~ipip_Agreeableness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model)

# Visualizar o modelo

plot(dados$iptc~dados$ipip_Conscientiousness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)

# Aleatoriedade dos resíduos
plot(model$residuals, pch = 16, col = "red")
```
```{r}

model = lm(tci_TaskOrientation ~ipip_Agreeableness + ipip_Conscientiousness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model)

# Visualizar o modelo


# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)

# Aleatoriedade dos resíduos
plot(model$residuals, pch = 16, col = "red")
```
```{r}

model = lm(tci_TaskOrientation ~ipip_Agreeableness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model)

# Visualizar o modelo

plot(dados$tci_TaskOrientation~dados$ipip_Agreeableness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)

# Aleatoriedade dos resíduos
plot(model$residuals, pch = 16, col = "red")
```

```{r}

model = lm(tci_TaskOrientation ~ipip_Conscientiousness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dados$tci_TaskOrientation~dados$ipip_Conscientiousness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)


```
```{r}

model = lm(tci_ParticipativeSafety ~ipip_Agreeableness + ipip_Conscientiousness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo



# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)


```
```{r}

model = lm(tci_ParticipativeSafety ~ipip_Agreeableness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dados$tci_ParticipativeSafety~dados$ipip_Agreeableness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```

```{r}

model = lm(tci_ParticipativeSafety ~ipip_Conscientiousness, data = dados) #Create the linear regression
summary(model) #Review the results
plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dados$tci_ParticipativeSafety~dados$ipip_Conscientiousness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```


```{r}
# stepwise forward regression - IPTC
model <- lm(iptc ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_forward_p(model, details = TRUE)
```
```{r}
# stepwise forward regression - IPTC
model <- lm(iptc ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_all_possible(model)

```
```{r}

# stepwise forward regression - IPTC
model <- lm(iptc ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_best_subset(model, details = TRUE)
```
```{r}

# stepwise forward regression - IPTC
model <- lm(iptc ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_both_p(model, details = TRUE)
```


```{r}
# stepwise forward regression - TeamVision
model <- lm(tci_TeamVision ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_forward_p(model, details = TRUE)
```
```{r}
# stepwise forward regression - TeamVision
model <- lm(tci_TeamVision ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_all_possible(model)

```
```{r}

# stepwise forward regression - TeamVision
model <- lm(tci_TeamVision ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_best_subset(model, details = TRUE)
```
```{r}

# stepwise forward regression - TeamVision
model <- lm(tci_TeamVision ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_both_p(model, details = TRUE)
```

```{r}
# stepwise forward regression - TaskOrientation
model <- lm(tci_TaskOrientation ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_forward_p(model, details = TRUE)
```
```{r}
# stepwise forward regression - TaskOrientation
model <- lm(tci_TaskOrientation ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_all_possible(model)

```
```{r}

# stepwise forward regression - TaskOrientation
model <- lm(tci_TaskOrientation ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_best_subset(model, details = TRUE)
```
```{r}

# stepwise forward regression - TaskOrientation
model <- lm(tci_TaskOrientation ~ ipip_Extraversion + ipip_Agreeableness + ipip_Conscientiousness + ipip_Neuroticism + ipip_Openness, data = dadosEquipesGrandes)
ols_step_both_p(model, details = TRUE)
```

