---
title: "analiseDescritivaMBTI"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(broom)
library(modelr)
library(here)
library(ggplot2)
library(reshape2)
library(grid)
library("GGally")
library(tidyverse)
library(psych)
library(summarytools)
library("dplyr")
library("ggpubr")
library (rcompanion)
library(readxl)
theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)


```

```{r ETL}
dadosMBTI = read_csv(here::here("IPIP-TCI-Subjects-MBTI_final.csv")) 

cols(
  codigoSHA = col_character(),
  projetoAtual = col_character(),
  Role = col_character(),
  xpPosGraduate = col_double(),
  xpPosGraduatedVirtus = col_double(),
  Age = col_double(),
  Gender = col_character(),
  tci_TeamVision = col_double(),
  tci_TaskOrientation = col_double(),
  tci_SupportForInovation = col_double(),
  tci_ParticipativeSafety = col_double(),
  iptc = col_double(),
  ipip_Extraversion = col_double(),
  ipip_Agreeableness = col_double(),
  ipip_Conscientiousness = col_double(),
  ipip_Neuroticism = col_double(),
  ipip_Openness = col_double()
)

```
```{r}

#psych::describe(dados)

#Média, Mediana, Desvio padrão, coeficiente de variação, minimo e máximo
descr(dadosMBTI, stats = c("mean", "med", "sd", "cv", "min", "max"), transpose = TRUE)

```
```{r}
#summary
dfSummary(dadosMBTI)
```
```{r}
#Frequencia da idade por grupos

AgeGrp <- as.character(cut(dadosMBTI$Age, breaks=c(20,25,30,35,40,Inf),
          labels=c('20-25', '26-30', '31-35', '36-40', 'Over 40')))

with(dadosMBTI, stby(data = Age, INDICES = AgeGrp, 
                   FUN = descr))

```
```{r}
#Frequencia da xp pos graduado por grupos

PosGraduateGrp <- as.character(cut(dadosMBTI$xpPosGraduate, breaks=c(0,3,6,10,14,Inf),
          labels=c('0-3', '4-6', '7-10', '11-14', 'Over 14')))

with(dadosMBTI, stby(data = Age, INDICES = PosGraduateGrp, 
                   FUN = descr))

```
```{r}
#Frequencia da xp pos graduado no virtus por grupos

PosGraduateGrpVirtus <- as.character(cut(dadosMBTI$xpPosGraduatedVirtus, breaks=c(0,3,6,10,14,Inf),
          labels=c('0-3', '4-6', '7-10', '11-14', 'Over 14')))

with(dadosMBTI, stby(data = Age, INDICES = PosGraduateGrpVirtus, 
                   FUN = descr))

```

```{r}
#boxplot(dados$tci_TeamVision, xlim = c(0, 2), ylim = c(0, 5))
#bboxplot(dados$tci_TaskOrientation, xlim = c(0, 2), ylim = c(0, 5))
#babline(h=1,col="red",lty=2)
#babline(h=2,col="red",lty=2)
#babline(h=3,col="red",lty=2)
#babline(h=4,col="red",lty=2)
#babline(h=5,col="red",lty=2)

mar.orig <- par()$mar
par(mar=c(9,4,3,0))
boxplot(dadosMBTI$mbti_EXTROVERTIDO, dadosMBTI$mbti_INTUITIVO, dadosMBTI$mbti_PENSANTE, dadosMBTI$mbti_JULGADOR,
main = "MBTI",
names = c("Extrovertido", "Intuitivo", "Pensante", "Julgador"),
las = 1,
xlim = c(0, 18),
ylim = c(0, 100),
at = c(2, 6, 10, 14),
varwidth = TRUE,
ylab = "Score of MBTI traits"

)

#abline(h=1,col="red",lty=2)
#abline(h=2,col="red",lty=2)
#abline(h=3,col="red",lty=2)
#abline(h=4,col="red",lty=2)
#abline(h=5,col="red",lty=2)
#par(mar = mar.orig)
```
```{r}
#boxplot(dados$tci_TeamVision, xlim = c(0, 2), ylim = c(0, 5))
#bboxplot(dados$tci_TaskOrientation, xlim = c(0, 2), ylim = c(0, 5))
#babline(h=1,col="red",lty=2)
#babline(h=2,col="red",lty=2)
#babline(h=3,col="red",lty=2)
#babline(h=4,col="red",lty=2)
#babline(h=5,col="red",lty=2)

mar.orig <- par()$mar
par(mar=c(9,5,3,0))
boxplot(dadosMBTI$tci_TeamVision, dadosMBTI$tci_TaskOrientation, dadosMBTI$tci_SupportForInovation, dadosMBTI$tci_ParticipativeSafety, dadosMBTI$iptc,
main = "Team climate factors’ scores",
names = c("Vision", "Task Orientation", "Support for Inovation", "Participative Safety", "IPTC"),
las = 1,
xlim = c(0, 18),
ylim = c(0, 5),
at = c(0.5, 3.5, 8.5, 13.5, 17),
varwidth = TRUE,
ylab = "Score of team climate factor"

)

abline(h=1,col="red",lty=2)
abline(h=2,col="red",lty=2)
abline(h=3,col="red",lty=2)
abline(h=4,col="red",lty=2)
abline(h=5,col="red",lty=2)
#par(mar = mar.orig)
```

```{r}

mar.orig <- par()$mar
par(mar=c(9,5,3,0))
boxplot(dadosMBTI$ipip_Extraversion, dados$ipip_Agreeableness, dados$ipip_Conscientiousness, dados$ipip_Neuroticism,dados$ipip_Openness,
main = "Personality traits’ scores",
names = c("Extraversion", "Agreeableness", "Conscientiousness", "Neuroticism", "Openness"),
las = 1,
xlim = c(0, 10),
ylim = c(0, 100),
varwidth = TRUE,
at = c(0.5, 2.5, 5, 7.5, 9.5),
ylab = "Score of personality trait"

)

abline(h=30,col="red",lty=2)
abline(h=70,col="red",lty=2)

#par(mar = mar.orig)
```



```{r}
#Density plot - MBTI


ggdensity(dadosMBTI$mbti_EXTROVERTIDO, main = "Density plot of mbti_EXTROVERTIDO",
          xlab = "mbti_EXTROVERTIDO")

ggdensity(dadosMBTI$mbti_INTUITIVO, main = "Density plot of mbti_INTUITIVO",
          xlab = "mbti_INTUITIVO")

ggdensity(dadosMBTI$mbti_PENSANTE, main = "Density plot of mbti_PENSANTE",
          xlab = "mbti_PENSANTE")

ggdensity(dadosMBTI$mbti_JULGADOR, main = "Density plot of mbti_JULGADOR",
          xlab = "tmbti_JULGADOR")

```

```{r}
#Q-Q plot - MBTI


ggqqplot(dadosMBTI$mbti_EXTROVERTIDO, main = "Density plot of mbti_EXTROVERTIDO",
          xlab = "mbti_EXTROVERTIDO")

ggqqplot(dadosMBTI$mbti_INTUITIVO, main = "Density plot of mbti_INTUITIVO",
          xlab = "mbti_INTUITIVO")

ggqqplot(dadosMBTI$mbti_PENSANTE, main = "Density plot of mbti_PENSANTE",
          xlab = "mbti_PENSANTE")

ggqqplot(dadosMBTI$mbti_JULGADOR, main = "Density plot of mbti_JULGADOR",
          xlab = "mbti_JULGADOR")


```
```{r}
#Shapiro-Wilk’s test - MBTI


shapiro.test(dadosMBTI$mbti_EXTROVERTIDO)

shapiro.test(dadosMBTI$mbti_INTUITIVO)

shapiro.test(dadosMBTI$mbti_PENSANTE)

shapiro.test(dadosMBTI$mbti_JULGADOR)


```

```{r}
#Density plot - TCI


ggdensity(dadosMBTI$tci_TeamVision, main = "Density plot of tci_TeamVision",
          xlab = "tci_TeamVision")

ggdensity(dadosMBTI$tci_TaskOrientation, main = "Density plot of tci_TaskOrientation",
          xlab = "tci_TaskOrientation")

ggdensity(dadosMBTI$tci_SupportForInovation, main = "Density plot of tci_SupportForInovation",
          xlab = "tci_SupportForInovation")

ggdensity(dadosMBTI$tci_ParticipativeSafety, main = "Density plot of tci_ParticipativeSafety",
          xlab = "tci_ParticipativeSafety")

ggdensity(dadosMBTI$iptc, main = "Density plot of iptc",
          xlab = "iptc")
```

```{r}
#Q-Q plot - TCI


ggqqplot(dadosMBTI$tci_TeamVision, main = "Density plot of tci_TeamVision",
          xlab = "tci_TeamVision")

ggqqplot(dadosMBTI$tci_TaskOrientation, main = "Density plot of tci_TaskOrientation",
          xlab = "tci_TaskOrientation")

ggqqplot(dadosMBTI$tci_SupportForInovation, main = "Density plot of tci_SupportForInovation",
          xlab = "tci_SupportForInovation")

ggqqplot(dadosMBTI$tci_ParticipativeSafety, main = "Density plot of tci_ParticipativeSafety",
          xlab = "tci_ParticipativeSafety")

ggqqplot(dadosMBTI$iptc, main = "Density plot of iptc",
          xlab = "iptc")
```
```{r}
#Shapiro-Wilk’s test - TCI


shapiro.test(dadosMBTI$tci_TeamVision)

shapiro.test(dadosMBTI$tci_TaskOrientation)

shapiro.test(dadosMBTI$tci_SupportForInovation)

shapiro.test(dadosMBTI$tci_ParticipativeSafety)

shapiro.test(dadosMBTI$iptc)
```

```{r}
#Density plot - IPIP


ggdensity(dadosMBTI$ipip_Extraversion, main = "Density plot of ipip_Extraversion",
          xlab = "ipip_Extraversion")

ggdensity(dadosMBTI$ipip_Agreeableness, main = "Density plot of ipip_Agreeableness",
          xlab = "ipip_Agreeableness")

ggdensity(dadosMBTI$ipip_Conscientiousness, main = "Density plot of ipip_Conscientiousness",
          xlab = "ipip_Conscientiousness")

ggdensity(dadosMBTI$ipip_Neuroticism, main = "Density plot of ipip_Neuroticism",
          xlab = "ipip_Neuroticism")

ggdensity(dadosMBTI$ipip_Openness, main = "Density plot of ipip_Openness",
          xlab = "ipip_Openness")
```
```{r}
#Q-Q plot - IPIP


ggqqplot(dadosMBTI$ipip_Extraversion, main = "Density plot of ipip_Extraversion",
          xlab = "ipip_Extraversion")

ggqqplot(dadosMBTI$ipip_Agreeableness, main = "Density plot of ipip_Agreeableness",
          xlab = "ipip_Agreeableness")

ggqqplot(dadosMBTI$ipip_Conscientiousness, main = "Density plot of ipip_Conscientiousness",
          xlab = "ipip_Conscientiousness")

ggqqplot(dadosMBTI$ipip_Neuroticism, main = "Density plot of ipip_Neuroticism",
          xlab = "ipip_Neuroticism")

ggqqplot(dadosMBTI$ipip_Openness, main = "Density plot of ipip_Openness",
          xlab = "ipip_Openness")
```

```{r}
#Shapiro-Wilk’s test 0 IPIP

options(scipen = 999)
shapiro.test(dadosMBTI$ipip_Extraversion)

shapiro.test(dadosMBTI$ipip_Agreeableness)

shapiro.test(dadosMBTI$ipip_Conscientiousness)

shapiro.test(dadosMBTI$ipip_Neuroticism)

shapiro.test(dadosMBTI$ipip_Openness)
```





```{r}

selecionar = select(dadosMBTI, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc)
cor(selecionar, method = "spearman")

```
```{r}

selecionar = select(dadosMBTI, mbti_EXTROVERTIDO, mbti_INTUITIVO, mbti_PENSANTE, mbti_JULGADOR)
cor(selecionar, method = "spearman")

```
```{r}

selecionar = select(dadosMBTI, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc, mbti_EXTROVERTIDO, mbti_INTUITIVO, mbti_PENSANTE, mbti_JULGADOR)
cor(selecionar, method = "spearman")

```
```{r}

selecionar = select(dadosMBTI, tci_TeamVision, tci_SupportForInovation, tci_TaskOrientation, tci_ParticipativeSafety, iptc, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "spearman")

```
```{r}

selecionar = select(dadosMBTI, mbti_EXTROVERTIDO, mbti_INTUITIVO, mbti_PENSANTE, mbti_JULGADOR, ipip_Extraversion, ipip_Agreeableness,ipip_Conscientiousness,ipip_Neuroticism,ipip_Openness)
cor(selecionar, method = "spearman")

```
```{r}
options(scipen = 999)



model = lm(iptc ~mbti_PENSANTE + mbti_JULGADOR, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}

options(scipen = 999)



model = lm(iptc ~mbti_PENSANTE, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$iptc~dadosMBTI$mbti_PENSANTE)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}



model = lm(iptc ~mbti_JULGADOR, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$iptc~dadosMBTI$mbti_JULGADOR)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}




model = lm(tci_ParticipativeSafety ~mbti_PENSANTE, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results


plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$tci_ParticipativeSafety~dadosMBTI$mbti_PENSANTE)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}



model = lm(tci_TeamVision ~ mbti_INTUITIVO, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$tci_TeamVision ~dadosMBTI$mbti_INTUITIVO)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}




model = lm(tci_SupportForInovation ~mbti_PENSANTE, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results


plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$tci_SupportForInovation~dadosMBTI$mbti_PENSANTE)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}




model = lm(tci_TaskOrientation~mbti_PENSANTE, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results



plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$tci_TaskOrientation ~dadosMBTI$mbti_PENSANTE)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}



model = lm(iptc~ipip_Agreeableness, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$iptc~dadosMBTI$ipip_Agreeableness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}


model = lm(iptc~ipip_Conscientiousness, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo


plot(dadosMBTI$iptc~dadosMBTI$ipip_Conscientiousness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
```{r}



model = lm(tci_ParticipativeSafety~ipip_Agreeableness, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$tci_ParticipativeSafety~dadosMBTI$ipip_Agreeableness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```

```{r}



model = lm(tci_SupportForInovation~ipip_Agreeableness, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$tci_SupportForInovation~dadosMBTI$ipip_Agreeableness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```




```{r}



model = lm(tci_TaskOrientation~ipip_Agreeableness, data = dadosMBTI) #Create the linear regression
summary(model) #Review the results

plot(model$residuals, pch = 16, col = "red")

plot(model)

# Visualizar o modelo

plot(dadosMBTI$tci_TaskOrientation~dadosMBTI$ipip_Agreeableness)
abline(model)

# Teste a normalidade dos resíduos
shapiro.test(model$residuals)

durbinWatsonTest(model)

bptest(model)

# Avalie a homogeneidade das variâncias
plot(rstudent(model) ~ fitted(model), pch = 19)
abline(h = 0, lty = 2)
```
